export const outstandingPRData = [
  {
    prNo: 87651,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2026-01-28 02:51:39",
    requiredBefore: "2026-02-28",
    vesselNameOrOther: "",
    remarks: "TV Box Replacement",
    rfpNo: "",
  },
  {
    prNo: 87539,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2026-01-02 15:33:03",
    requiredBefore: "2026-02-02",
    vesselNameOrOther: "",
    remarks: "New AP for CON",
    rfpNo: "",
  },
  {
    prNo: 87517,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-12-26 11:07:07",
    requiredBefore: "2026-01-26",
    vesselNameOrOther: "",
    remarks: "16GB DDR4 3200Mhz RAM",
    rfpNo: "",
  },
  {
    prNo: 87429,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-12-02 11:28:13",
    requiredBefore: "2026-01-02",
    vesselNameOrOther: "",
    remarks: "BCP/DRP, Hosting of Wallem IT System",
    rfpNo: "",
  },
  {
    prNo: 87247,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-10-15 10:15:45",
    requiredBefore: "2025-10-15",
    vesselNameOrOther: "",
    remarks: "Replacement printer toner",
    rfpNo: "",
  },
  {
    prNo: 87233,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-10-13 09:10:55",
    requiredBefore: "2025-10-17",
    vesselNameOrOther: "",
    remarks: "ACASIS DisplayLink Multi-Monitor Docking Station",
    rfpNo: "",
  },
  {
    prNo: 87702,
    requestedBy: "MARIA",
    prStatus: "Pending",
    prType: "Vessel Service",
    dateCreated: "2026-02-08 14:22:15",
    requiredBefore: "2026-02-25",
    vesselNameOrOther: "MV Ocean Pioneer",
    remarks: "Engine maintenance and spare parts",
    rfpNo: "RFP-2026-003",
  },
  {
    prNo: 87695,
    requestedBy: "ALEX",
    prStatus: "In Review",
    prType: "Office Supplies",
    dateCreated: "2026-02-07 09:45:22",
    requiredBefore: "2026-02-20",
    vesselNameOrOther: "",
    remarks: "Monthly office stationery and printer supplies",
    rfpNo: "",
  },
  {
    prNo: 87688,
    requestedBy: "SARAH",
    prStatus: "Approved",
    prType: "SOC Feeder/Co-loader",
    dateCreated: "2026-02-05 16:30:41",
    requiredBefore: "2026-02-15",
    vesselNameOrOther: "",
    remarks: "Container transportation services - Shanghai to Los Angeles",
    rfpNo: "RFP-2026-001",
  },
  {
    prNo: 87673,
    requestedBy: "MIKE",
    prStatus: "Pending",
    prType: "Company Car",
    dateCreated: "2026-02-03 11:15:33",
    requiredBefore: "2026-03-01",
    vesselNameOrOther: "",
    remarks: "Fleet vehicle replacement - Toyota Camry 2026",
    rfpNo: "",
  },
  {
    prNo: 87665,
    requestedBy: "LISA",
    prStatus: "In Review",
    prType: "Job Order",
    dateCreated: "2026-02-01 13:20:07",
    requiredBefore: "2026-02-28",
    vesselNameOrOther: "",
    remarks: "IT infrastructure upgrade and network maintenance",
    rfpNo: "",
  },
  {
    prNo: 87658,
    requestedBy: "DAVID",
    prStatus: "Approved",
    prType: "Trucking Services",
    dateCreated: "2026-01-30 08:45:18",
    requiredBefore: "2026-02-14",
    vesselNameOrOther: "",
    remarks: "Container delivery from port to warehouse",
    rfpNo: "RFP-2026-002",
  },
  {
    prNo: 87642,
    requestedBy: "ANNA",
    prStatus: "Rejected",
    prType: "Chassis Leasing",
    dateCreated: "2026-01-25 10:30:55",
    requiredBefore: "2026-02-25",
    vesselNameOrOther: "",
    remarks: "40ft chassis lease for container operations",
    rfpNo: "",
  },
  {
    prNo: 87635,
    requestedBy: "ROBERT",
    prStatus: "Pending",
    prType: "Vessel Service",
    dateCreated: "2026-01-22 07:15:42",
    requiredBefore: "2026-02-22",
    vesselNameOrOther: "MV Pacific Star",
    remarks: "Hull cleaning and underwater inspection",
    rfpNo: "",
  },
  {
    prNo: 87628,
    requestedBy: "EMILY",
    prStatus: "Approved",
    prType: "Others",
    dateCreated: "2026-01-20 15:40:29",
    requiredBefore: "2026-02-10",
    vesselNameOrOther: "",
    remarks: "Security system installation and monitoring services",
    rfpNo: "",
  },
  {
    prNo: 87621,
    requestedBy: "JAMES",
    prStatus: "In Review",
    prType: "Office Supplies",
    dateCreated: "2026-01-18 12:25:14",
    requiredBefore: "2026-02-05",
    vesselNameOrOther: "",
    remarks: "Ergonomic office chairs and desk accessories",
    rfpNo: "",
  },
  {
    prNo: 87614,
    requestedBy: "SOPHIA",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2026-01-15 09:50:36",
    requiredBefore: "2026-02-15",
    vesselNameOrOther: "",
    remarks: "Industrial-grade wireless access points",
    rfpNo: "",
  },
  {
    prNo: 87607,
    requestedBy: "MICHAEL",
    prStatus: "Pending",
    prType: "Job Order",
    dateCreated: "2026-01-12 14:05:21",
    requiredBefore: "2026-01-30",
    vesselNameOrOther: "",
    remarks: "HVAC system maintenance and filter replacement",
    rfpNo: "",
  },
  {
    prNo: 87598,
    requestedBy: "OLIVIA",
    prStatus: "Approved",
    prType: "Vessel Service",
    dateCreated: "2026-01-10 11:35:47",
    requiredBefore: "2026-02-10",
    vesselNameOrOther: "MV Atlantic Crown",
    remarks: "Navigation equipment calibration and certification",
    rfpNo: "RFP-2026-004",
  },
  {
    prNo: 87591,
    requestedBy: "DANIEL",
    prStatus: "In Review",
    prType: "Trucking Services",
    dateCreated: "2026-01-08 16:20:13",
    requiredBefore: "2026-01-25",
    vesselNameOrOther: "",
    remarks: "Heavy machinery transportation services",
    rfpNo: "",
  },
  {
    prNo: 87584,
    requestedBy: "JESSICA",
    prStatus: "Rejected",
    prType: "Company Car",
    dateCreated: "2026-01-05 13:15:58",
    requiredBefore: "2026-02-05",
    vesselNameOrOther: "",
    remarks: "Executive vehicle upgrade request",
    rfpNo: "",
  },
  {
    prNo: 87577,
    requestedBy: "KEVIN",
    prStatus: "Approved",
    prType: "SOC Feeder/Co-loader",
    dateCreated: "2026-01-03 10:40:26",
    requiredBefore: "2026-01-20",
    vesselNameOrOther: "",
    remarks: "Weekly container feeder service - Asia to Europe",
    rfpNo: "RFP-2025-045",
  },
  {
    prNo: 87570,
    requestedBy: "AMY",
    prStatus: "Pending",
    prType: "Others",
    dateCreated: "2025-12-31 08:25:39",
    requiredBefore: "2026-01-31",
    vesselNameOrOther: "",
    remarks: "Training and certification programs for staff",
    rfpNo: "",
  },
  {
    prNo: 87563,
    requestedBy: "CHRIS",
    prStatus: "Approved",
    prType: "Chassis Leasing",
    dateCreated: "2025-12-28 15:10:12",
    requiredBefore: "2026-01-28",
    vesselNameOrOther: "",
    remarks: "20ft and 40ft chassis long-term lease agreement",
    rfpNo: "",
  },
  {
    prNo: 87556,
    requestedBy: "RACHEL",
    prStatus: "In Review",
    prType: "Purchase",
    dateCreated: "2025-12-25 12:55:44",
    requiredBefore: "2026-01-25",
    vesselNameOrOther: "",
    remarks: "High-capacity UPS systems for data center",
    rfpNo: "",
  },
];

export const prColumns = [
    { key: "prNo", label: "PR NO" },
    { key: "requestedBy", label: "Requested by" },
    { key: "prStatus", label: "PR Status" },
    { key: "prType", label: "PR TYPE" },
    { key: "dateCreated", label: "Date Created" },
    { key: "requiredBefore", label: "Required Before" },
    { key: "vesselNameOrOther", label: "Vessel Name/Other" },
    { key: "remarks", label: "REMARKS" },
    { key: "rfpNo", label: "RFP NO" },
];

export const ROWS_PER_PAGE = 5;
