export const outstandingPRData = [
  {
    prNo: 87651,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2026-01-28 02:51:39",
    requiredBefore: "2026-02-28",
    vesselNameOrOther: "",
    remarks: "TV Box Replacement",
    rfpNo: "",
  },
  {
    prNo: 87539,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2026-01-02 15:33:03",
    requiredBefore: "2026-02-02",
    vesselNameOrOther: "",
    remarks: "New AP for CON",
    rfpNo: "",
  },
  {
    prNo: 87517,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-12-26 11:07:07",
    requiredBefore: "2026-01-26",
    vesselNameOrOther: "",
    remarks: "16GB DDR4 3200Mhz RAM",
    rfpNo: "",
  },
  {
    prNo: 87429,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-12-02 11:28:13",
    requiredBefore: "2026-01-02",
    vesselNameOrOther: "",
    remarks: "BCP/DRP, Hosting of Wallem IT System",
    rfpNo: "",
  },
  {
    prNo: 87247,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-10-15 10:15:45",
    requiredBefore: "2025-10-15",
    vesselNameOrOther: "",
    remarks: "Replacement printer toner",
    rfpNo: "",
  },
  {
    prNo: 87233,
    requestedBy: "JOEY",
    prStatus: "Approved",
    prType: "Purchase",
    dateCreated: "2025-10-13 09:10:55",
    requiredBefore: "2025-10-17",
    vesselNameOrOther: "",
    remarks: "ACASIS DisplayLink Multi-Monitor Docking Station",
    rfpNo: "",
  },
];

export const prColumns = [
    { key: "prNo", label: "PR NO" },
    { key: "requestedBy", label: "Requested by" },
    { key: "prStatus", label: "PR Status" },
    { key: "prType", label: "PR TYPE" },
    { key: "dateCreated", label: "Date Created" },
    { key: "requiredBefore", label: "Required Before" },
    { key: "vesselNameOrOther", label: "Vessel Name/Other" },
    { key: "remarks", label: "REMARKS" },
    { key: "rfpNo", label: "RFP NO" },
];

export const ROWS_PER_PAGE = 5;
