export const requestForOptions = ["Purchase - Quantifiable", "Vessel Service - Quantifiable", "Office Supplies - Quantifiable", "SOC Feeder/Co-loader - Quantifiable", "Company Car - Quantifiable", "Job Order - NonQuantifiable", "Trucking Services - Quantifiable", "Chassis Leasing - NonQuantifiable", "Pro Tank Frt Charges - NonQuantifiable", "Others - NonQuantifiable",];
export const accountOfOptions = ["Principal/Vessel", "TAD", "CLAD", "WPSI/Accounting", "WPSI/Admin", "WPSI/HR", "WPSI/Operations", "WPSI/MIS", "WPSI/Legal", "WPSI/Purchasing", "WPSI"];
export const companiesOptions = [
    "ABERGEN",
    "Aberjen Ship Chandling",
    "Aberjen Shipchandling & Maritime Services",
    "AIMERMED MERCHANDISING",
    "Alan Bacal",
    "ALFA LAVAL PHILIPPINES, INC.",
    "All Premium Balloons & Party Needs Corp.",
    "AMARR MARINE INC.",
    "Amerasia Int'l. Terminal Serv., Inc.",
    "AQUA INTRA WATER REFILLING STATION",
    "AR-GOS INSPECTION SERVICES, INC. (AISI)",
    "Asian Terminals Inc. (ATI)",
    "Assist Tow Marine, Inc.",
    "ATI Batangas (former Aries Arrastre Service, In)",
    "ATI South Harbor",
    "Ayda Security Agency",
    "B.P. Mata & Co.",
    "Bacolod Tugboat Services Corp.",
    "BACOLOD-PULUPANDAN HARBOR PILOT COMPANY",
    "BAUAṄ SHIP WATER SUPPLY CORPORATION",
    "BEN LINE AGENCIES PHILIPPINES, INC.",
    "Blackbolt K9 Services",
    "Buena Vista Travel n' Tours",
    "C. B BARANGAY ENTERPRISES",
    "CARGO DATA EXCHANGE CENTER, INC.",
    "Carolinas Trading",
    "CATENA SECURITY, INC.",
    "Cebu Pilots Association",
    "CHEM-J AIRE REF & AIRCON TECH REPAIR SVC",
    "CHENG LIE NAVIGATION CO., LTD.",
    "CITY GARDEN SUITES",
    "COCOLIFE HEALTHCARE",
    "Corestream",
    "COTS Freight International",
    "Court Meridian Hotel & Suites",
    "Danilo Tolentino",
    "DAVAO GULF MARINE SERVICES, INC.",
    "Davao Pilots Association",
    "Davao Tugboat and Allied Services, Inc."
];

export const plateNumberOptions = [
  "XTR-4921",
  "MNL-8375",
  "QZP-1048",
  "RKV-5629",
  "JTY-9083",
  "BHG-7214",
  "WQC-3567",
  "LZN-8452",
  "KDX-1907",
  "FVR-6730",
];

export const officeSuppliesOptions = [
    "Bond Paper A4",
    "Bond Paper Legal",
    "Ballpen (Blue)",
    "Ballpen (Black)", 
    "Ballpen (Red)",
    "Pencil #2",
    "Mechanical Pencil",
    "Marker (Permanent)",
    "Marker (Whiteboard)",
    "Highlighter",
    "Correction Tape",
    "Correction Fluid",
    "Stapler",
    "Staple Wire",
    "Paper Clips",
    "Binder Clips",
    "Rubber Bands",
    "Paper Fastener",
    "Manila Folder",
    "Expanding Folder",
    "Clear Book",
    "Ring Binder",
    "Index Divider",
    "Sticky Notes",
    "Envelope (Long)",
    "Envelope (Short)",
    "Calculator",
    "Scissors",
    "Ruler",
    "Tape Dispenser",
    "Scotch Tape",
    "Masking Tape",
    "Glue Stick",
    "Liquid Glue",
    "Puncher (2-hole)",
    "Puncher (3-hole)",
    "Stamp Pad",
    "Rubber Stamp",
    "Toner Cartridge",
    "Ink Cartridge",
    "USB Flash Drive",
    "CD-R",
    "DVD-R",
    "File Cabinet",
    "Desk Organizer",
    "Waste Basket",
    "Desk Lamp",
    "Extension Cord",
    "Power Strip",
    "Document Holder"
];

export const approvalOptions = ["JUN", "LAY", "PCV", "JRC", "ANC", "JEFF", "JLV", "EDU", "MAM", "LAS", "MRC"];